// ==UserScript==
// @name          DuckDuckGo
// @namespace     http://userstyles.org
// @description	  better
// @author        ceberous
// @homepage      https://creatitees.info
// @include       http://duckduckgo.com/*
// @include       https://duckduckgo.com/*
// @include       http://*.duckduckgo.com/*
// @include       https://*.duckduckgo.com/*
// @run-at        document-start
// @version       0.1
// ==/UserScript==
(function() {var css = [
	"/* ==== DUCKDUCKGO - Multi-Columns v.5 (new5) ==== */",
	"",
	"/* (new3) - LOGO - === */",
	".header__logo-wrap {",
	"    left: 90px !important;",
    "    background-color: #f7f7f7;",
	"    width: 58px !important;",
	"}",
	"",
	"/* (new3) SEARCH FIELD - === */",
	".header__content.header__search {",
	"    margin-left: 88px;",
	"/* width: 1800px !important; */",
	"    width: 93% !important;",
	"}",
	"#search_form_input  {",
	"    color: black !important;",
	"}",
	"",
    "#header {",
    "  background-color: #f7f7f7;",
    "}",
    "",
	"/* (new3) - FIRST ROW RESULTS - IMAGE/RESULTS TITLE VIEW - ARROW left/right - === */",
	".tile-nav.can-scroll, ",
	".tile-nav.can-scroll::after {",
	"    background-color: #de5833 !important;",
	"    color: #fff;",
	"}",
	"",
	"/* new3) - SEACH FIELD - === */",
	".search--header {",
	"    height: 38px;",
	"    padding-left: 9px;",
	"    border-right-width: 5em !important;",
	"    background-color: #02f702 !important;",
	"}",
	"#search_form {",
	"/* width: 100% !important; */",
	"/* max-width: 1800px !important; */",
	"}",
	"",
	"/* (new3) SUPP - NO VIDEO RESULTS BLOCK CONTAINER - === */",
	"/* #zero_click_wrapper {",
	"    display: none;",
	"} */",
	"",
	"/* (new3) - RESULTS ITEMS CONTAINER - HOVER - ",
	".result__snippet b, ",
	"=== */",
	".result.results_links_deep.highlight_d.highlight {",
	"/* border: 1px solid red !important; */",
    " background-color: #02f702;",
	"}",
	"",
	".result.results_links_deep.highlight_d.highlight .result__check::before {",
	"    display: inline-block !important;",
	"    left: -33px !important;",
	"    right: 655px !important;",
	"    content: \"☑\";",
	"    float: right;",
	"    font-family: \"ddg-serp-icons\" !important;",
	"    font-style: normal;",
	"    font-variant: normal;",
	"    font-weight: normal !important;",
	"    line-height: 1;",
	"    text-decoration: none !important;",
	"    text-transform: none;",
	"/* outline: 1px solid red !important; */",
	"}",
	"",
    "body {",
    "    background-color: #000000;",
    "}",
    "",
	".result__check__tt::before {",
	"    position: absolute;",
	"    display: block;",
	"    content: \"\";",
	"    left: 1.5em;",
	"    margin-left: -0.5em;",
	"}",
	"",
	"/* (new2) - RESULTS HIGHLIGHTING - ",
	".result__snippet b, ",
	"=== */",
	".result.results_links_deep.highlight_d.highlight {",
	"/* background: red !important; */",
	"    border: 1px solid red !important;",
	"}",
	".result.results_links_deep.highlight_d .result__snippet b {",
	"    color: tomato !important;",
	"}",
	"",
	"/* (new3) RESULTS VISITED CHECK - === */",
	".result__check {",
	"    position: absolute;",
	"    width: 1em;",
	"    top: 1.6em !important;",
	"    margin-right: 1em;",
	"    right: 93% !important;",
	"    font-size: 0.8em;",
	"    white-space: nowrap;",
	"/* border: 1px solid violet !important; */",
	"}",
	"",
	".result:not(:hover) .result__body .result__check ,",
	".result:hover .result__body .result__check {",
	"    height: 100% ! important;",
	"    min-height: 118px !important;",
	"    max-height: 118px !important;",
	"    width: 100%! important;",
	"    min-width: 20px ! important;",
	"    max-width: 20px ! important;",
	"    margin-top: -24px !important;",
	"    left: 2px !important;",
	"    padding: 30px 5px 2px 2px  !important;",
	"    border-left: 2px solid gray !important;",
	"    background: rgba(115, 108, 108, 0.28) !important;",
	"}",
	".result:not(:hover) .result__body .result__check:visited ,",
	".result:hover .result__body .result__check:visited {",
	"    border-left: 2px solid red !important;",
	"}",
	"/* (new3) - VISITED CHECK - ALWAYS VISIBLE - === */",
	".result__check:visited:before {",
	"    color: #205984  ! important;",
	"    background: rgba(115, 108, 108, 0.28) !important;",
	"}",
	".result__check .result__check,",
	".result__check:hover .result__check__tt {",
	"    height: 20px !important;",
	"    top: 7px !important;",
	"    left: -9px!important;",
	"    visibility: visible;",
	"    opacity: 1;",
	"    transition-delay: 0.75s;",
    "    background-color: #02f702",
	"}",
	" ",
	"/* (new3) - RESULTS CONTAINER - ==== */",
	"/* .results  */",
	".cw {",
	"    max-width: 110% ! important;",
	"    min-width: 110% ! important;",
	"    left: -90px ! important;",
	"/* outline: 1px solid green ! important; */",
	"}",
	"",
	".results-wrapper {",
	"    min-width: 91.2% ! important;",
	"    max-width: 91.2% ! important;",
	"    padding-right: 0px !important;",
	"/* outline: 1px solid red ! important; */",
	"}",
	".cw #links_wrapper.results-wrapper #links.results {",
	"    display: inline-block !important;",
	"    float: left !important;",
	"    max-width: 99% ! important;",
	"    min-width:90% ! important;",
	"/* outline: 1px solid red ! important; */",
	"}",
	"",
	"/* (new5) INFINITE SCROLL OK - RESULT CONTAINER - PAGE/s - WITH/WITHOUT LINES SEPARATOR - === */",
	"/* #links .results_links_deep  */",
	"#links .result:not(.result--sep):not(.result--more) {",
	"    display: inline-block !important;",
	"    float: left !important;",
	"    min-height: 155px ! important;",
	"    max-height: 155px ! important;",
	"    min-width: 32.7% ! important;",
	"    max-width: 32.7% ! important;",
	"    margin-right: 4px ! important;",
	"    margin-bottom: 3px !important;",
	"    padding: 1px 1px 1px 35px ! important;",
	"    border: 1px solid gray ! important;",
	"/* border: 1px solid violet ! important; */",
	"}",
	".result__body.links_main.links_deep {",
	"    margin-top: -20px;",
	"}",
	"",
	"/* ==== (new5)  RESULT CONTAINER - PAGE - TOOGLE BUTTON LOCALISATION (in test)  / RESULTS MORE / NO RESULTS RELATED / LINES SEPARATOR ==== */*",
	"",
	"/* (new5) TOOGLE BUTTON LOCALISATION  */",
	"",
	" .results--sidebar.js-results-sidebar .region-switch  {",
	"    position: absolute !important;",
	"    right: -0.7em !important;",
	"    top: -20px !important;",
	"    text-align: right;",
	"    z-index: 200 !important;",
	"}",
	".region-switch .switch {",
	"    float: left;",
	"    height: 14px !important;",
	"    line-height: 14px !important;",
	"    margin-right: 8px;",
	"}",
	".switch__knob {",
	"    position: absolute;",
	"    display: block;",
	"    height: 12px !important;",
	"    width: 12px !important;",
	"    top: 1px !important;",
	"    left: 2px;",
	"    border-radius: 9px;",
	"    transition: all 0.1s ease 0s, all 0s linear 0s, left 0.3s ease-in-out 0s;",
	"    background-color: #fff;",
	"}",
	".is-on .switch__knob {",
	"    left: 32px !important;",
	"}",
	".switch__on {",
	"    position: absolute;",
	"    line-height: 12px !important;",
	"    left: 10px;",
	"    color: #fff;",
	"    font-size: 12px !important;",
	"}",
	".region-flag__wrap--small {",
	"    height: 14px !important;",
	"    width: 14px !important;",
	"}",
	".region-flag__wrap--small .region-flag__img {",
	"    height: 14px !important;",
	"}",
	"",
	"/* (new5) RESULTS MORE BUTTON - AT BOTTOM WIDER - === */",
	".result.result--more {",
	"    position: absolute !important;",
	"    bottom: 0px!important;",
	"    left: 0px !important;",
	"    width: 50% !important;",
	"    margin-left: 30% !important;",
	"    margin-bottom: -10px!important;",
	"}",
	"",
	"/* (new5) NO RESULTS BLOCK - === */",
	".no-results {",
	"    position: relative !important;",
	"    display: inline-block !important;",
	"    min-width: 99% ! important;",
	"    max-width: 99% ! important;",
	"    bottom: 0 !important;",
	"    padding-left: 0.75em;",
	"    padding-top: 2em;",
	"    margin-left: 0% !important;",
	"    text-align: center !important;",
	"/* outline: 1px solid peru ! important; */",
	"}",
	"",
	"/* (new5) LINES SEPARATOR - === */",
	"#links .result--sep  {",
	"    float: left!important;",
	"    min-height: 10px ! important;",
	"    max-height: 10px ! important;",
	"    line-height: 5px ! important; ",
	"    min-width: 97.4% ! important;",
	"    max-width: 97.4% ! important;",
	"    margin-top: 0px !important;",
	"    margin-left: 20px ! important;",
	"    bottom: -5px !important;",
	"/* outline: 1px solid peru ! important; */",
	"}",
	"",
	"/* (nrew5) LINES SEPARATORS - COUNTER (move middle) - === */",
	".result--sep--hr::before {",
	"    position: absolute;",
	"    display: block;",
	"    content: \"\";",
	"    height: 1px;",
	"    left: 10px;",
	"    right: 20px;",
	"    top: 0.25em !important;",
	"    background-color: #02f702;",
	"}",
	".result__pagenum--side {",
	"    position: absolute;",
	"    width: 1.6em;",
	"    height: 1.6em;",
	"    line-height: 1.6em;",
	"    top: -6px !important;",
	"    left: 50% !important;",
	"    padding: 0;",
	"    border-radius: 50%;",
	"    text-align: center;",
	"}",
	"",
	"",
	"/* (new4) RESULTS - ADAPTATION FOR GM LINKYPLUS - IMAGES LINKS - ",
	"https://duckduckgo.com/?q=ShowAllGroups+-+by+vispillo",
	"=== */",
	".linkifyplus img {",
	"    max-width: 10% !important;",
	"    float: left!important;",
	"    padding: 1px !important;",
	"    clear: none!important;",
	"}",
	"",
	"/* (new3) RESULTS - COUNTER */",
	"#links .results_links_deep {",
	"    counter-increment: myIndex ! important;",
	"}",
	"#links .results_links_deep:before {",
	"    display: inline-block ! important;",
	"    min-width: 15px ! important;",
	"    margin-left: -27px ! important;",
	"    content: counter(myIndex, decimal-leading-zero);",
	"    border-radius: 8px ! important;",
	"    font-size: 10px ! important;",
	"    text-align: center ! important;",
	"    color: red ! important;",
	"    background: gold ! important;",
	"    z-index: 10 !important;",
	"}",
	"",
	"",
	"",
	"/* BACK to TOP BUTTON - === */",
	".results--sidebar--mid {",
	"    position: fixed;",
	"    display: inline-block ! important;",
	"    max-width: 44em;",
	"    width: 20px ! important;",
	"    height: 10px ! important;",
	"    left: -150px !important;",
	"    top: 20px ! important;",
	"    z-index: 5;",
	"}",
	"",
	"/* TOP HEADER */",
	".has-zcm .header-wrap:after {",
	"    height: 9px !important;",
	"}",
	"",
	"",
	"/* === END ==== */"
].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node); 
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
